service: Lifecycle-Backup-and-Remove-EC2-Files

provider:
  name: aws
  runtime: python3.11

functions:
  lifecycle-backup-and-remove-ec2-files:
    handler: handler.lambda_handler
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "ec2:DescribeInstances"
        Resource: "*"
      - Effect: "Allow"
        Action:
          - "s3:PutObject"
          - "s3:GetObject"
        Resource: "*"
      - Effect: "Allow"
        Action:
          - "ssm:GetParameter"
        Resource: "*"
    environment:
      CRON_EXPRESSION: ${env:CRON_EXPRESSION}
    events:
      - schedule: cron(${env:CRON_EXPRESSION})

plugins:
  - serverless-python-requirements