service: lambda-schedule

provider:
  name: aws
  runtime: python3.8
  region: sa-east-1

plugins:
  - serverless-iam-roles-per-function

functions:
  scaleDeployments:
    handler: scaleDeployments.lambda_handler
    timeout: 180
    memorySize: 128
    events:
      - schedule:
          rate:
            - cron(0 10 ? * 1-5 *)
            - cron(0 2 * * ? *) 

    iamRoleStatements:
      - Effect: Allow
        Action:
          - ssm:GetParameter
        Resource: arn:aws:ssm:${self:provider.region}:*:parameter/parameter-k8s