service: SERVICE-NAME

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8

functions:
  triggerActionsSandbox:
    handler: triggerWorkflow.handler
    events:
      - schedule:
          rate: cron(0 21 1 * ? *)
          enabled: true

package:
  exclude:    
    - __pycache__/**